# Generated by Django 5.2 on 2025-04-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderelement_delete_orderelements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderelement',
            old_name='count',
            new_name='quantity',
        ),
    ]
