# Generated by Django 5.2 on 2025-05-01 17:06

import django.core.validators
from django.db import migrations, models


def add_price(apps, _):
    OrderElement = apps.get_model("foodcartapp","OrderElement")
    elements = OrderElement.objects.select_related("product")
    for element in elements.iterator():
        element.price = element.quantity * element.product.price
        element.save()
class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_rename_count_orderelement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderelement',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена заказа'),
        ),
        migrations.RunPython(add_price)
    ]
