# Generated by Django 5.2 on 2025-05-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_orderelement_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('M', 'Передан менеджеру'), ('R', 'Передан ресторану'), ('C', 'Передан курьеру'), ('P', 'Обработанный')], db_index=True, default='M', max_length=1, verbose_name='Статус'),
        ),
    ]
