# Generated by Django 5.2 on 2025-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('C', 'Наличные'), ('N', 'Безналичные')], db_index=True, default='C', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
